### ISSUE TITLE
Restart action as per demo app doesn't work

### ISSUE THREAD

**Issue by grobbie** [canonical/charm-rolling-ops#14] opened 2024-02-20 10:04 UTC
## Steps to reproduce

* I've implemented the rolling ops lib in my charm [runs-like-a-charm](https://github.com/grobbie/runs-like-a-charm/tree/master).
* I've implemented an action that works the same as [the example action](https://github.com/canonical/charm-rolling-ops/blob/4bae5c031cb7a8d5fd3819ace1f1496c87c0aae4/src/charm.py#L79) in the charm-rolling-ops repo.
* I run the action `juju run runs-like-a-charm/leader rolling-restart interval=0`
* The leader reboots as expected after 60s of grace that I've set with `shutdown -r +1`
* The peers don't do anything - this is wrong

## Expected behavior
* The peers should also be triggered to reboot in a cascade, after the leader reboots

## Actual behavior
* The peers are not rebooting, only the leader

## Versions
Operating system: 
* 22.04 LTS

Juju CLI: 
* 3.3.1

Juju agent: 
* 3.3.1

## Log output
Juju debug log: 
* nothing noteworthy in the logs

**Comment by marcoppenheimer** [comment] 2024-02-24 00:30
The `rolling-ops` only ensures that a function call is not ran concurrently between Units in an Application.

When you run `juju run runs-like-a-charm/leader rolling-restart interval=0`, only the leader Unit gets that event.

When it handles that event, it checks if any other peer-related unit is currently doing your callback (in your charm's case, `_restart`). It finds that none of them are running it (because only the leader got that event), and as such restarts. 

If you want to run that on every unit, you would do something like:

```
juju run runs-like-a-charm/0 runs-like-a-charm/1 runs-like-a-charm/2 rolling-restart interval=0
```

**Comment by taurus-forever** [comment] 2024-04-22 21:03
The charm has been refreshed to use the latest lib version, tested and documented: https://charmhub.io/rolling-ops

P.S. Rob, I also got into the same trap initially thinking lib will propagate execution on peers. Nope (c) as designed. :-D
Feel free to reopen if your bug-report is still topical, closing to keep the house clean.

**Closed by taurus-forever** 2024-04-22 21:03 UTC
Labels: bug
